### ISSUE TITLE
Error in calculating revise answer score

### ISSUE THREAD

**Issue by impact-rm** [EQ-bench/EQ-Bench#25]
When I call the eq-bench with -revise enabled it returns "! Error: 4 emotions were not returned" and revised_answers: {}

**Comment by impact-rm** [comment]
When I call the eq-bench with -revise enabled it returns "! Error: 4 emotions were not returned" and revised_answers: {}

**Comment by impact-rm** [comment]
The problem is solved by increasing the COMPLETION_TOKENS (which is set to 60) in eq_bench_utils.py. As it's the value  parsed to max_tokens of openai.

**Comment by sam-paech** [comment]
Ah, thank you. I overlooked this, will fix.
