### ISSUE TITLE
ooba not parsing in .cfg

### ISSUE THREAD

**Issue by zisismp4** [EQ-bench/EQ-Bench#37]
Whenever ooba is selected as inference engine, there is error _Failed to parse line_.

**Comment by sam-paech** [comment]
Could you paste your config file here?

**Comment by zisismp4** [comment]
just try uncommenting myrun5 example:
_myrun5, Mistral, mistralai/Mistral-7B-Instruct-v0.2, , None, 1, ooba, --loader transformers --gpu-memory 12, --exclude "*.bin"_
also try myrun2 replacing transformers with ooba:
_myrun2, Llama-v2, meta-llama/Llama-2-7b-chat-hf, /path/to/local/lora/adapter, 8bit, 3, **ooba**, , ,_

**Comment by sam-paech** [comment]
The error messages can be a bit opaque, sorry about that.

Can you check if you are getting any errors *above* the error saying it failed to parse that line?

I just downloaded it fresh and ran it with that line uncommented, and got this trace:

```
ooba_launch_script not set in config.cfg
Failed to parse line in config:
myrun5, Mistral, mistralai/Mistral-7B-Instruct-v0.2, , None, 1, ooba, --loader transformers --gpu-memory 12, --exclude "*.bin"
```

So, the first error is the one actually causing the issue.

**Comment by zisismp4** [comment]
Yes, that is what I am getting. So ithe _Failed to parse line in config_ error is caused from _ooba_launch_script not set in config.cfg_  ?

**Comment by sam-paech** [comment]
Yeah you just need to set ooba_launch_script to the path where ooba is installed on your machine. 

e.g. per the example:

ooba_launch_script = ~/text-generation-webui/start_linux.sh

**Comment by zisismp4** [comment]
Thanks!
