### ISSUE TITLE
Add some of the new 100B+ models to the leaderboard

### ISSUE THREAD

**Issue by cosmojg** [EQ-bench/EQ-Bench#5]
It would be really cool to see how some of the more recent megamerges stack up against the rest of the competition, especially those which build on top of [miqu-1-70b](https://huggingface.co/miqudev/miqu-1-70b). Specifically, I think it would be interesting to benchmark the EQ of the following models:

* [miqu-1-120b](https://huggingface.co/wolfram/miqu-1-120b) ([miqu-1-70b](https://huggingface.co/miqudev/miqu-1-70b) + [miqu-1-70b](https://huggingface.co/miqudev/miqu-1-70b))

* [miquliz-120b-v2.0](https://huggingface.co/wolfram/miquliz-120b-v2.0) ([miqu-1-70b](https://huggingface.co/miqudev/miqu-1-70b) + [lzlv_70b](https://huggingface.co/lizpreciatior/lzlv_70b_fp16_hf))

* [lzlv_70b](https://huggingface.co/lizpreciatior/lzlv_70b_fp16_hf) (for comparison with its descendants)

And if it's not way too big to benchmark...

* [TheProfessor-155b](https://huggingface.co/abacusai/TheProfessor-155b) (cognitivecomputations/dolphin-2.2-70b + WizardLM/WizardMath-70B-V1.0 + migtissera/SynthIA-70B-v1.2b + epfl-llm/meditron-70b)

**Comment by sam-paech** [comment]
Thx for the suggestions. I actually did some of these already, just added the latest to the leaderboard.

    wolfram/miquliz-120b-v2.0	82.21
    alpindale/miquella-120b	82.15
    migtissera/Tess-72B-v1.5b	81.78

I'll see if I can get TheProfessor to run, that one looks like a beast. Not sure if I'll get to lzlv & miquliz soon but they're on my list.

**Comment by cosmojg** [comment]
@sqrkl Oh sweet, that's awesome! Thank you for all of your hard work! Out of curiosity, what kind of hardware are you using to run these benchmarks?

**Comment by sam-paech** [comment]
I spin up instances on runpod or vast.ai. My local hardware is not really capable of most of these models.

**Comment by sam-paech** [comment]
Just added TheProfessor-155b.
